### ISSUE TITLE
Remove ksmstarter.com from all.json immediately

### ISSUE THREAD

**Issue by flisko** [polkadot-js/phishing#567] opened 2021-10-08 07:57 UTC
Hello,

Please remove “ksmstarter.com” from the blacklist immediately. We can not believe you have decided to add us based on a random persons tweet.
Our platform supports Moonriver network ,which will be added in the near future.

We are more than happy to go through a live demo with you to combat any scepticism you may have. 
Moreover, we do not believe a tweet constitutes enough legal ground to deny service to our current community. In this regard, we are also happy to liaise our legal advisors with yours.

Best Regards,
KSMStarter Team

**Comment by cooldude78** [comment] 2021-10-08 08:14
While I am not from web3 what so ever, it is better to have communicated KSM starter to the general public as not a scam .  Even if that means talking in the unofficial Kusama and unofficial Polkadot TG groups, on youtube and have a clear disclaimer on your website. etc.. To promote the fact KSM starter is not a scam. Which I am glad it is not.

**Comment by jacogr** [comment] 2021-10-08 08:47
Duplicate of https://github.com/polkadot-js/phishing/issues/566

**Closed by jacogr** 2021-10-08 08:47 UTC
Labels: <duplicate>
